# Generated by Django 3.2.5 on 2022-08-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='media/usuario/default_user.png', upload_to='usuario'),
        ),
    ]
