# Generated by Django 3.2.5 on 2022-08-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20220810_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
    ]
