# Generated by Django 3.2.5 on 2022-08-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20220810_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
