# Generated by Django 3.2.5 on 2022-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario/user-default.png', upload_to='usuario'),
        ),
    ]
