# Generated by Django 3.2.5 on 2022-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario/default_user.png', upload_to='usuario'),
        ),
    ]
