# Generated by Django 3.2.5 on 2022-08-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='media/noticia/default.png', upload_to='noticia'),
        ),
    ]
