# Generated by Django 3.2.5 on 2022-08-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(null=True),
        ),
    ]
