# Generated by Django 3.2.5 on 2022-08-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_noticia_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='media/noticia/default.png', upload_to='media/noticia'),
        ),
    ]
