# Generated by Django 3.2.5 on 2022-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0007_auto_20220805_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
