# Generated by Django 3.2.5 on 2022-08-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0010_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
