# Generated by Django 3.2.5 on 2022-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0015_alter_noticia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
