# Generated by Django 3.2.5 on 2022-08-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0017_alter_noticia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
