# Generated by Django 3.2.5 on 2022-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0018_remove_noticia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='noticia/default.png', upload_to='noticia'),
        ),
    ]
