# Generated by Django 3.2.5 on 2022-08-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0020_remove_noticia_destacada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha']},
        ),
    ]
