# Generated by Django 3.2.5 on 2022-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0022_categoria_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='estado',
            new_name='activo',
        ),
    ]
