# Generated by Django 3.2.5 on 2022-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
