# Generated by Django 3.2.5 on 2022-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220825_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
