# Generated by Django 3.2.5 on 2022-08-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0018_remove_noticia_slug'),
        ('comentario', '0002_auto_20220801_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticia.noticia'),
        ),
    ]
