# Generated by Django 3.2.5 on 2022-08-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_comentario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('fecha',)},
        ),
    ]
