# Generated by Django 3.2.5 on 2022-08-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0005_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
