# Generated by Django 3.2.5 on 2022-08-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0012_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha']},
        ),
    ]
